<!-- GitHub star -->
<a class="github-button" href="https://github.com/AloneMonkey/MonkeyDev" data-icon="octicon-star" data-show-count="true" aria-label="Star MonkeyDev on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/AloneMonkey/MonkeyDev/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork MonkeyDev on GitHub">Fork</a>
<!-- Github Button -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
